### ISSUE TITLE
Text boxes are too tall

### ISSUE THREAD

**Issue by Ralith** [SecondHalfGames/yakui#110] opened 2023-10-23 01:17 UTC
e.g. the `textbox` example is consistently more than two lines tall, even when updated or initialized with one line of text or the empty string. A similar effect is visible in a column layout.

**Comment by Ralith** [comment] 2023-10-23 01:29
The cursor is *also* too tall; see e.g.:
<img width="353" alt="image" src="https://github.com/SecondHalfGames/yakui/assets/104558/dde3e2de-3669-42b7-8ee3-a54972cba648">

**Comment by Ralith** [comment] 2023-10-23 01:32
Here's the same textbox initialized with three lines, with the cursor on the top line:

<img width="316" alt="image" src="https://github.com/SecondHalfGames/yakui/assets/104558/7d0cc89a-67ed-4b02-af41-e941cfca2eba">

**Comment by LPGhatguy** [comment] 2023-10-23 01:46
Found to be caused by scale factor not being part of some of the cursor math.

Fixed in cb45454dffaa41b1dddc3aadce4ac29a9a3d901f.

**Closed by LPGhatguy** 2023-10-23 01:46 UTC
